services:

  postgres:
    image: postgres:15
    container_name: project_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: project_backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/app_db
    ports:
      - "5000:5000"

volumes:
  postgres_data: