services:

  postgres:
    image: postgres:16
    container_name: finance_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_123
      POSTGRES_DB: personal_finance_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  server:
    build: ./server
    container_name: finance_server
    restart: always

    ports:
      - "5000:5000"

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: pass_123
      DATABASE_NAME: personal_finance_db
      JWT_SECRET: supersecretkey

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  postgres_data: